# HYPRLAND CONFIG ---- All settings are sourced from organized modules

# MATUGEN COLORS
source = ~/.config/hypr/colors.conf

# MONITOR CONFIG
source = ~/.config/hypr/modules/monitors.conf

# KEYBINDS CONFIG
source = ~/.config/hypr/modules/keybinds.conf

# ENVIRONMENT VARIABLE CONFIG
source = ~/.config/hypr/modules/environment.conf

# AUTOSTART CONFIG
source = ~/.config/hypr/modules/autostart.conf

# ANIMATIONS CONFIG
source = ~/.config/hypr/modules/animations.conf

# PROGRAMS CONFIG
source = ~/.config/hypr/modules/programs.conf

# INPUT CONFIG
source = ~/.config/hypr/modules/input.conf

# LOOK AND FEEL CONFIG
source = ~/.config/hypr/modules/looks.conf

# WORKSPACE CONFIG
# source = ~/.config/hypr/modules/workspaces.conf



windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
