
# An alpha background
$surface_alpha = rgba(0f14174d)


$image = Pictures/Wallpapers/LA_Sunset.jpg
$background = rgba(19120cff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$error = rgba(ffb4abff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$error_container = rgba(93000aff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$inverse_on_surface = rgba(372f28ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$inverse_primary = rgba(88521cff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$inverse_surface = rgba(efe0d6ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_background = rgba(efe0d6ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_error = rgba(690005ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_error_container = rgba(ffdad6ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_primary = rgba(4c2700ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_primary_container = rgba(ffdcc1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_primary_fixed = rgba(2e1500ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_primary_fixed_variant = rgba(6b3b04ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_secondary = rgba(412c19ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_secondary_container = rgba(ffdcc1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_secondary_fixed = rgba(2a1707ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_secondary_fixed_variant = rgba(5a422eff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_surface = rgba(efe0d6ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_surface_variant = rgba(d6c3b6ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_tertiary = rgba(2d330eff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_tertiary_container = rgba(dfe7b1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_tertiary_fixed = rgba(181e00ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$on_tertiary_fixed_variant = rgba(434a22ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$outline = rgba(9e8e82ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$outline_variant = rgba(51443bff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$primary = rgba(ffb779ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$primary_container = rgba(6b3b04ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$primary_fixed = rgba(ffdcc1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$primary_fixed_dim = rgba(ffb779ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$scrim = rgba(000000ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$secondary = rgba(e3c0a5ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$secondary_container = rgba(5a422eff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$secondary_fixed = rgba(ffdcc1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$secondary_fixed_dim = rgba(e3c0a5ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$shadow = rgba(000000ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$source_color = rgba(e6b083ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface = rgba(19120cff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_bright = rgba(413731ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_container = rgba(261e18ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_container_high = rgba(312822ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_container_highest = rgba(3c332cff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_container_low = rgba(221a14ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_container_lowest = rgba(140d08ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_dim = rgba(19120cff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_tint = rgba(ffb779ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$surface_variant = rgba(51443bff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$tertiary = rgba(c3cb97ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$tertiary_container = rgba(434a22ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$tertiary_fixed = rgba(dfe7b1ff)

$image = Pictures/Wallpapers/LA_Sunset.jpg
$tertiary_fixed_dim = rgba(c3cb97ff)

