# Monitor Config

monitor=DP-4,1920x1080@165,0x0,1,transform,1
monitor=DP-5,1920x1080@165,3000x0,1
monitor=DP-6,1920x1080@165,1080x0,1

# Assign Monitors to Workspaces
workspace = 1, monitor:DP-6
workspace = 2, monitor:DP-6
workspace = 3, monitor:DP-6
workspace = 4, monitor:DP-6
workspace = 5, monitor:DP-5
workspace = 6, monitor:DP-5
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-4
workspace = 9, monitor:DP-4
workspace = 10, monitor:DP-4
